export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const LOAD_BEEHIVES_SUCCESS = 'LOAD_BEEHIVES_SUCCESS';
export const CREATE_BEEHIVES_SUCCESS = 'CREATE_BEEHIVES_SUCCESS';
export const DELETED_BEEHIVE = 'DELETED_BEEHIVE';




export const UPDATE_BEEHIVES_SUCCESS = 'UPDATE_BEEHIVES_SUCCESS';
export const LOAD_HIVE_TYPE_SUCCESS = 'LOAD_HIVE_TYPE_SUCCESS';


export const LOAD_SUPERBOXES_SUCCESS = 'LOAD_SUPERBOXES_SUCCESS';
export const CREATE_SUPERBOXES_SUCCESS = 'CREATE_SUPERBOXES_SUCCESS';
export const DELETED_SUPERBOX = 'DELETED_SUPERBOX';




export const UPDATE_SUPERBOXES_SUCCESS = 'UPDATE_SUPERBOXES_SUCCESS';
export const LOAD_SUPER_TYPE_SUCCESS = 'LOAD_SUPER_TYPE_SUCCESS';
